services:
  frontend:
    image: ghcr.io/freshlyavocado/solevia-frontend:latest
    container_name: solevia-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always

  db:
    image: mysql:8.0
    container_name: solevia-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: backend
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image: ghcr.io/freshlyavocado/solevia-backend:latest
    container_name: solevia-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: backend
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 12345

  webserver:
    image: nginx:alpine
    container_name: solevia-webserver
    restart: always
    ports:
      - "8080:80" 
    volumes:
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www
    depends_on:
      - backend

volumes:
  db_data:
